// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fflrmrkkbpcqftlibmbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmbHJtcmtrYnBjcWZ0bGlibWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjkxOTUsImV4cCI6MjA2ODk0NTE5NX0.-zl-EuQdMl3zneJ-BoyczxDdABiaRx3cHt5QQ_C2E1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});